# Packages

In [1]:
import numpy as np
import pandas as pd

# Setup

In [2]:
# directories
wd = '/Users/lneumann/Documents/'
data_dir = wd + 'Data/'
database_dir = wd + 'Products/dense_gas_letter/database/'

# ALMOND
almond_galaxies = ['ngc0628','ngc1097','ngc1365','ngc1385','ngc1511','ngc1546','ngc1566','ngc1672','ngc1792','ngc2566',
                   'ngc2903','ngc2997','ngc3059','ngc3521','ngc3621','ngc4303','ngc4321','ngc4535','ngc4536','ngc4569',
                   'ngc4826','ngc5248','ngc5643','ngc6300','ngc7496']
almond_res_list = ['18.6as', '19.4as', '20.6as', '19.9as', '17.6as', '18.9as', '19.7as', '18.2as', '18.7as', '18.5as',
                   '18.3as', '20.4as', '16.7as', '21.1as', '18.9as', '20.2as', '19.6as', '22.8as', '21.5as', '19.2as',
                   '18.7as', '19.9as', '18.0as', '17.7as', '17.9as']

# EMPIRE
empire_galaxies = ['ngc0628', 'ngc2903', 'ngc3184', 'ngc3627', 'ngc4254', 'ngc4321', 'ngc5055', 'ngc5194', 'ngc6946']
empire_res_list = ['33.3as', '33.3as', '33.3as', '33.3as', '33.3as', '33.3as', '33.3as', '33.3as', '33.3as']

# combine
galaxy_list = almond_galaxies + empire_galaxies
res_list = almond_res_list + empire_res_list
survey_list = ['almond'] * len(almond_galaxies) + ['empire'] * len(empire_galaxies)
survey_ref_list = ['Neumann23'] * len(almond_galaxies) + ['Jim√©nez-Donaire19'] * len(empire_galaxies)

# x-axis data and labels
xlabels = ['Sd_mol_MW', 'Sd_mol_SL24', 'Sd_star', 'P_DE_MW', 'P_DE_SL24']  # labels of database filennames
xlabels_stacking = ['INT_VAL_SD_MOL_MW', 'INT_VAL_SD_MOL_SL24', 'INT_VAL_SD_STAR', 'INT_VAL_P_DE_MW', 'INT_VAL_P_DE_SL24']  # labels of the stacking files
xlabels_df = ['SD_mol (MW) [Msun/pc2]', 'SD_mol (SL24) [Msun/pc2]', 'SD_star [Msun/pc2]', 'P_DE (MW) [kB.K/cm3]', 'P_DE (SL24) [kB.K/cm3]'] # labels of the database entries to be saved

# constants to compute surface densities and dense gas fraction
alpha_co10 = 4.35  # [M_Sun/pc^2/(K km/s)] (Bolatto et al. 2013)
alpha_hcn = 15  # [M_Sun/pc^2/(K km/s)] (Schinnerer & Leroy 2024)

# Sightline database

In [3]:
# create arrays to store data for database
glxy_array, survey_array, survey_refs_array = [], [], []
ra_array, dec_array, rgal_array = [],[],[]
W_co10_array, W_co10_array_err = [],[]
W_co21_array, W_co21_array_err = [],[]
W_hcn_array, W_hcn_array_err = [],[]
W_hcop_array, W_hcop_array_err = [],[]
Sd_sfr_array, Sd_sfr_array_err = [],[]
Sd_sfr_incl_array, Sd_sfr_incl_array_err = [],[]
Sd_mol_mw_array, Sd_mol_mw_array_err = [],[]
Sd_mol_sl24_array, Sd_mol_sl24_array_err = [],[]
Sd_dense_array, Sd_dense_array_err = [],[]
Sd_star_array, Sd_star_array_err = [],[]
P_DE_mw_array, P_DE_mw_array_err = [],[]
P_DE_sl24_array, P_DE_sl24_array_err = [],[]


# loop over galaxies
for glxy, res, survey, survey_ref in zip(galaxy_list, res_list, survey_list, survey_ref_list):

    # directories of ALMOND and EMPIRE data
    if survey == 'almond':
        pystruct_dir = data_dir + 'ALMOND/pystruct/'
    elif survey == 'empire':
        pystruct_dir = data_dir + 'EMPIRE/pystruct/'
    
    ###### LOAD PYSTRUCTURE DATA ######

    # load pystructure database
    pystruct_file = pystruct_dir + '%s_data_struct_%s_spb2.npy' % (glxy, res)
    struct = np.load(pystruct_file, allow_pickle = True).item()
    
    # coordinates
    ra = struct['ra_deg']
    dec = struct['dec_deg']
    rgal = struct['rgal_kpc']
    incl = np.deg2rad(struct['incl_deg'])

    # molecular line data
    R_21 = struct['INT_VAL_R21_SL24']
    if survey == 'almond':
        W_co21 = struct['INT_VAL_CO21']
        W_co21_err = struct['INT_UC_CO21']
        W_co10 = W_co21 / R_21
        W_co10_err = W_co21_err / R_21
    elif survey == 'empire':
        W_co10 = struct['INT_VAL_CO10']
        W_co10_err = struct['INT_UC_CO10']
        W_co21 = W_co10 * R_21
        W_co21_err = W_co10_err * R_21
    W_hcn = struct['INT_VAL_HCN10']
    W_hcn_err = struct['INT_UC_HCN10']
    W_hcop = struct['INT_VAL_HCOP10']
    W_hcop_err = struct['INT_UC_HCOP10']

    # SFR data
    Sd_sfr = struct['INT_VAL_SFR_Z0MGS'] * np.cos(incl)  # with inclination correction
    Sd_sfr_err = struct['INT_UC_SFR_Z0MGS'] * np.cos(incl)    
    
    # physical quantities
    Sd_mol_mw = struct['INT_VAL_SD_MOL_MW']
    Sd_mol_mw_err = struct['INT_UC_SD_MOL_MW']        
    Sd_mol_sl24 = struct['INT_VAL_SD_MOL_SL24']
    Sd_mol_sl24_err = struct['INT_UC_SD_MOL_SL24']
    Sd_dense = struct['INT_VAL_SD_DENSE']
    Sd_dense_err = struct['INT_UC_SD_DENSE']
    Sd_star = struct['INT_VAL_SD_STAR']
    Sd_star_err = struct['INT_UC_SD_STAR']
    P_DE_mw = struct['INT_VAL_P_DE_MW']
    P_DE_mw_err = struct['INT_UC_P_DE_MW']
    P_DE_sl24 = struct['INT_VAL_P_DE_SL24']
    P_DE_sl24_err = struct['INT_UC_P_DE_SL24']
    
    ###### APPEND TO DATABASE ######

    # galaxies and surveys
    glxy_array += [glxy]*len(rgal)
    survey_array += [survey.upper()]*len(rgal)
    survey_refs_array += [survey_ref]*len(rgal)

    # coordinates
    ra_array = np.concatenate((ra_array, ra))
    dec_array = np.concatenate((dec_array, dec))
    rgal_array = np.concatenate((rgal_array, rgal))
    
    # stacks
    W_co10_array = np.concatenate((W_co10_array, W_co10))
    W_co10_array_err = np.concatenate((W_co10_array_err, W_co10_err))
    W_co21_array = np.concatenate((W_co21_array, W_co21))
    W_co21_array_err = np.concatenate((W_co21_array_err, W_co21_err))
    W_hcn_array = np.concatenate((W_hcn_array, W_hcn))
    W_hcn_array_err = np.concatenate((W_hcn_array_err, W_hcn_err))
    W_hcop_array = np.concatenate((W_hcop_array, W_hcop))
    W_hcop_array_err = np.concatenate((W_hcop_array_err, W_hcop_err))
    Sd_sfr_array = np.concatenate((Sd_sfr_array, Sd_sfr))
    Sd_sfr_array_err = np.concatenate((Sd_sfr_array_err, Sd_sfr_err))
    Sd_sfr_incl_array = np.concatenate((Sd_sfr_incl_array, Sd_sfr/np.cos(incl)))
    Sd_sfr_incl_array_err = np.concatenate((Sd_sfr_incl_array_err, Sd_sfr_err/np.cos(incl)))
    Sd_mol_mw_array = np.concatenate((Sd_mol_mw_array, Sd_mol_mw))
    Sd_mol_mw_array_err = np.concatenate((Sd_mol_mw_array_err, Sd_mol_mw_err))
    Sd_mol_sl24_array = np.concatenate((Sd_mol_sl24_array, Sd_mol_sl24))
    Sd_mol_sl24_array_err = np.concatenate((Sd_mol_sl24_array_err, Sd_mol_sl24_err))
    Sd_dense_array = np.concatenate((Sd_dense_array, Sd_dense))
    Sd_dense_array_err = np.concatenate((Sd_dense_array_err, Sd_dense_err))
    Sd_star_array = np.concatenate((Sd_star_array, Sd_star))
    Sd_star_array_err = np.concatenate((Sd_star_array_err, Sd_star_err))
    P_DE_mw_array = np.concatenate((P_DE_mw_array, P_DE_mw))
    P_DE_mw_array_err = np.concatenate((P_DE_mw_array_err, P_DE_mw_err))
    P_DE_sl24_array = np.concatenate((P_DE_sl24_array, P_DE_sl24))
    P_DE_sl24_array_err = np.concatenate((P_DE_sl24_array_err, P_DE_sl24_err))


###### SAVE DATA ######

# make data frame
df = pd.DataFrame({'Survey' : survey_array,
                   'Galaxy': glxy_array, 
                   'R.A. [deg]': ra_array,
                   'Dec. [deg]': dec_array,
                   'rgal [kpc]': rgal_array,
                   'W_CO21 [K.km/s]': W_co21_array,
                   'e_W_CO21 [K.km/s]': W_co21_array_err, 
                   'W_CO10 [K.km/s]': W_co10_array,
                   'e_W_CO10 [K.km/s]': W_co10_array_err, 
                   'W_HCN [K.km/s]': W_hcn_array,
                   'e_W_HCN [K.km/s]': W_hcn_array_err,
                   'W_HCOP [K.km/s]': W_hcop_array,
                   'e_W_HCOP [K.km/s]': W_hcop_array_err,
                   'SD_mol (MW) [Msun/pc2]': Sd_mol_mw_array,
                   'e_SD_mol (MW) [Msun/pc2]': Sd_mol_mw_array_err, 
                   'SD_mol (SL24) [Msun/pc2]': Sd_mol_sl24_array,
                   'e_SD_mol (SL24) [Msun/pc2]': Sd_mol_sl24_array_err, 
                   'SD_dense [Msun/pc2]': Sd_dense_array,
                   'e_SD_dense [Msun/pc2]': Sd_dense_array_err, 
                   'SD_star [Msun/pc2]': Sd_star_array,
                   'e_SD_star [Msun/pc2]': Sd_star_array_err, 
                   'P_DE (MW) [kB.K/cm3]': P_DE_mw_array,
                   'e_P_DE (MW) [kB.K/cm3]': P_DE_mw_array_err, 
                   'P_DE (SL24) [kB.K/cm3]': P_DE_sl24_array,
                   'e_P_DE (SL24) [kB.K/cm3]': P_DE_sl24_array_err, 
                   'SD_SFR [Msun/yr/kpc2]': Sd_sfr_array,
                   'e_SD_SFR [Msun/yr/kpc2]': Sd_sfr_array_err,
                   'SD_SFR [Msun/yr/kpc2] (no inclination correction)': Sd_sfr_incl_array,
                   'e_SD_SFR [Msun/yr/kpc2] (no inclination correction)': Sd_sfr_incl_array_err,
                   'Reference' : survey_refs_array,
                  })

# save to file
fname_table = database_dir + 'almond_and_empire_database_sightlines.csv'
df.to_csv(fname_table, index=False)

In [4]:
df

,Survey,Galaxy,R.A. [deg],Dec. [deg],rgal [kpc],W_CO21 [K.km/s],e_W_CO21 [K.km/s],W_CO10 [K.km/s],e_W_CO10 [K.km/s],W_HCN [K.km/s],...,e_SD_star [Msun/pc2],P_DE (MW) [kB.K/cm3],e_P_DE (MW) [kB.K/cm3],P_DE (SL24) [kB.K/cm3],e_P_DE (SL24) [kB.K/cm3],SD_SFR [Msun/yr/kpc2],e_SD_SFR [Msun/yr/kpc2],SD_SFR [Msun/yr/kpc2] (no inclination correction),e_SD_SFR [Msun/yr/kpc2] (no inclination correction),Reference
0,ALMOND,ngc0628,24.167133,15.758992,4.377404,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neumann23
1,ALMOND,ngc0628,24.169822,15.758992,4.287825,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neumann23
2,ALMOND,ngc0628,24.172511,15.758992,4.244124,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neumann23
3,ALMOND,ngc0628,24.175199,15.758992,4.247716,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neumann23
4,ALMOND,ngc0628,24.177888,15.758992,4.298484,0.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neumann23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20732,EMPIRE,ngc6946,308.756481,60.209687,8.332447,0.0,0.0,0.0,0.0,0.0,...,0.115284,16941.623135,2977.690147,16941.623135,2977.690147,0.0,0.0,0.0,0.0,Jim√©nez-Donaire19
20733,EMPIRE,ngc6946,308.765806,60.209687,8.451495,0.0,0.0,0.0,0.0,0.0,...,0.115266,16301.709484,2721.915195,16301.709484,2721.915195,0.0,0.0,0.0,0.0,Jim√©nez-Donaire19
20734,EMPIRE,ngc6946,308.775131,60.209687,8.613610,0.0,0.0,0.0,0.0,0.0,...,0.115261,13385.752937,2484.069790,13385.752937,2484.069790,0.0,0.0,0.0,0.0,Jim√©nez-Donaire19
20735,EMPIRE,ngc6946,308.761149,60.213700,8.949394,0.0,0.0,0.0,0.0,0.0,...,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Jim√©nez-Donaire19
20736,EMPIRE,ngc6946,308.770475,60.213700,9.075816,0.0,0.0,0.0,0.0,0.0,...,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Jim√©nez-Donaire19